#!/bin/sh

if [ ! -f /usr/bin/wget ]; then
    echo "please install wget"
    exit 0
elif [ $UID -ne 0 ]; then
    echo "you need to be root"
    exit 0
else

    wget -P /tmp/ https://github.com/kiddlu/Win7-Themes/raw/master/Font/YaHei%20Mono.zip

    echo 'truetype folder creating...'

    mkdir -p /usr/share/fonts/truetype/yahei-mono

    echo 'mv font to truetype folder...'
    unzip /tmp/YaHei\ Mono.zip
    mv YaHei\ Mono.ttf /usr/share/fonts/truetype/yahei-mono/
    echo 'modifying font permissions...'

    chmod 644 /usr/share/fonts/truetype/yahei-mono/YaHei\ Mono.ttf

    echo 'installing font...'

    fc-cache -fv

    echo 'complete!!!'

fi
