#!/bin/sh

ps -ax | grep -v grep | grep emacs > /dev/null
if [ $? -ne 0 ]; then
    #/opt/emacs/bin/emacs -nw $*
    #exit 0
    emacs &
    #/opt/emacs/bin/emacs --daemon
    sleep 5
fi

emacsclient -n $*
#/opt/emacs/bin/emacs -nw $*
