#!/bin/sh

#ps -aW | grep -v grep | grep Emacs > /dev/null
ps -a | grep -v grep | grep emacs-w32 > /dev/null
if [ $? -ne 0 ]; then
    #/winix/Emacs/bin/runemacs.exe &
    /bin/emacs-w32.exe &
    sleep 5
fi

#/winix/Emacs/bin/emacsclient -n $*
/bin/emacsclient-w32.exe -n $*
